{"root": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense", "root_issues": [{"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2023-50782", "PkgName": "cryptography", "PkgIdentifier": {"PURL": "pkg:pypi/cryptography@41.0.7", "UID": "530b3bd5f3d283bb"}, "InstalledVersion": "41.0.7", "FixedVersion": "42.0.0", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-50782", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-cryptography: Bleichenbacher timing oracle attack against RSA decryption - incomplete fix for CVE-2020-25659", "Description": "A flaw was found in the python-cryptography package. This issue may allow a remote attacker to decrypt captured messages in TLS servers that use RSA key exchanges, which may lead to exposure of confidential or sensitive data.", "Severity": "HIGH", "CweIDs": ["CWE-208", "CWE-203"], "VendorSeverity": {"azure": 3, "cbl-mariner": 3, "ghsa": 3, "nvd": 3, "photon": 3, "redhat": 2, "ubuntu": 2}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V3Score": 7.5}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2023-50782", "https://bugzilla.redhat.com/show_bug.cgi?id=2254432", "https://github.com/openssl/openssl/pull/13817", "https://github.com/pyca/cryptography", "https://github.com/pyca/cryptography/issues/9785", "https://nvd.nist.gov/vuln/detail/CVE-2023-50782", "https://people.redhat.com/~hkario/marvin/", "https://ubuntu.com/security/notices/USN-6663-1", "https://ubuntu.com/security/notices/USN-6673-1", "https://ubuntu.com/security/notices/USN-6673-2", "https://www.couchbase.com/alerts/", "https://www.cve.org/CVERecord?id=CVE-2023-50782"], "PublishedDate": "2024-02-05T21:15:11.183Z", "LastModifiedDate": "2024-11-21T08:37:18.337Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-26130", "PkgName": "cryptography", "PkgIdentifier": {"PURL": "pkg:pypi/cryptography@41.0.7", "UID": "530b3bd5f3d283bb"}, "InstalledVersion": "41.0.7", "FixedVersion": "42.0.4", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-26130", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-cryptography: NULL pointer dereference with pkcs12.serialize_key_and_certificates when called with a non-matching certificate and private key and an hmac_hash override", "Description": "cryptography is a package designed to expose cryptographic primitives and recipes to Python developers. Starting in version 38.0.0 and prior to version 42.0.4, if `pkcs12.serialize_key_and_certificates` is called with both a certificate whose public key did not match the provided private key and an `encryption_algorithm` with `hmac_hash` set (via `PrivateFormat.PKCS12.encryption_builder().hmac_hash(...)`, then a NULL pointer dereference would occur, crashing the Python process. This has been resolved in version 42.0.4, the first version in which a `ValueError` is properly raised.", "Severity": "HIGH", "CweIDs": ["CWE-476"], "VendorSeverity": {"ghsa": 3, "nvd": 3, "oracle-oval": 3, "photon": 3, "redhat": 3, "ubuntu": 2}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-26130", "https://github.com/pyca/cryptography", "https://github.com/pyca/cryptography/commit/97d231672763cdb5959a3b191e692a362f1b9e55", "https://github.com/pyca/cryptography/pull/10423", "https://github.com/pyca/cryptography/security/advisories/GHSA-6vqw-3v5j-54x4", "https://github.com/pypa/advisory-database/tree/main/vulns/cryptography/PYSEC-2024-225.yaml", "https://linux.oracle.com/cve/CVE-2024-26130.html", "https://linux.oracle.com/errata/ELSA-2025-20364.html", "https://nvd.nist.gov/vuln/detail/CVE-2024-26130", "https://ubuntu.com/security/notices/USN-6673-1", "https://ubuntu.com/security/notices/USN-6673-3", "https://www.cve.org/CVERecord?id=CVE-2024-26130"], "PublishedDate": "2024-02-21T17:15:09.863Z", "LastModifiedDate": "2025-02-05T22:09:20.427Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-0727", "PkgName": "cryptography", "PkgIdentifier": {"PURL": "pkg:pypi/cryptography@41.0.7", "UID": "530b3bd5f3d283bb"}, "InstalledVersion": "41.0.7", "FixedVersion": "42.0.2", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-0727", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "openssl: denial of service via null dereference", "Description": "Issue summary: Processing a maliciously formatted PKCS12 file may lead OpenSSL\nto crash leading to a potential Denial of Service attack\n\nImpact summary: Applications loading files in the PKCS12 format from untrusted\nsources might terminate abruptly.\n\nA file in PKCS12 format can contain certificates and keys and may come from an\nuntrusted source. The PKCS12 specification allows certain fields to be NULL, but\nOpenSSL does not correctly check for this case. This can lead to a NULL pointer\ndereference that results in OpenSSL crashing. If an application processes PKCS12\nfiles from an untrusted source using the OpenSSL APIs then that application will\nbe vulnerable to this issue.\n\nOpenSSL APIs that are vulnerable to this are: PKCS12_parse(),\nPKCS12_unpack_p7data(), PKCS12_unpack_p7encdata(), PKCS12_unpack_authsafes()\nand PKCS12_newpass().\n\nWe have also fixed a similar issue in SMIME_write_PKCS7(). However since this\nfunction is related to writing data we do not consider it security significant.\n\nThe FIPS modules in 3.2, 3.1 and 3.0 are not affected by this issue.", "Severity": "MEDIUM", "CweIDs": ["CWE-476"], "VendorSeverity": {"alma": 2, "amazon": 2, "azure": 2, "cbl-mariner": 2, "ghsa": 2, "nvd": 2, "oracle-oval": 2, "photon": 2, "redhat": 1, "ubuntu": 1}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H", "V3Score": 5.5}, "nvd": {"V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H", "V3Score": 5.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H", "V3Score": 5.5}}, "References": ["http://www.openwall.com/lists/oss-security/2024/03/11/1", "https://access.redhat.com/errata/RHSA-2024:9088", "https://access.redhat.com/security/cve/CVE-2024-0727", "https://bugzilla.redhat.com/2257571", "https://bugzilla.redhat.com/2258502", "https://bugzilla.redhat.com/2259944", "https://bugzilla.redhat.com/2284243", "https://errata.almalinux.org/9/ALSA-2024-9088.html", "https://github.com/alexcrichton/openssl-src-rs/commit/add20f73b6b42be7451af2e1044d4e0e778992b2", "https://github.com/github/advisory-database/pull/3472", "https://github.com/openssl/openssl/commit/09df4395b5071217b76dc7d3d2e630eb8c5a79c2", "https://github.com/openssl/openssl/commit/775acfdbd0c6af9ac855f34969cdab0c0c90844a", "https://github.com/openssl/openssl/commit/d135eeab8a5dbf72b3da5240bab9ddb7678dbd2c", "https://github.com/openssl/openssl/pull/23362", "https://github.com/pyca/cryptography/commit/3519591d255d4506fbcd0d04037d45271903c64d", "https://github.openssl.org/openssl/extended-releases/commit/03b3941d60c4bce58fab69a0c22377ab439bc0e8", "https://github.openssl.org/openssl/extended-releases/commit/aebaa5883e31122b404e450732dc833dc9dee539", "https://linux.oracle.com/cve/CVE-2024-0727.html", "https://linux.oracle.com/errata/ELSA-2024-9088.html", "https://nvd.nist.gov/vuln/detail/CVE-2024-0727", "https://security.netapp.com/advisory/ntap-20240208-0006", "https://security.netapp.com/advisory/ntap-20240208-0006/", "https://ubuntu.com/security/notices/USN-6622-1", "https://ubuntu.com/security/notices/USN-6632-1", "https://ubuntu.com/security/notices/USN-6709-1", "https://ubuntu.com/security/notices/USN-7018-1", "https://www.cve.org/CVERecord?id=CVE-2024-0727", "https://www.openssl.org/news/secadv/20240125.txt"], "PublishedDate": "2024-01-26T09:15:07.637Z", "LastModifiedDate": "2025-05-29T16:15:31.96Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "GHSA-h4gh-qq45-vh27", "PkgName": "cryptography", "PkgIdentifier": {"PURL": "pkg:pypi/cryptography@41.0.7", "UID": "530b3bd5f3d283bb"}, "InstalledVersion": "41.0.7", "FixedVersion": "43.0.1", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://github.com/advisories/GHSA-h4gh-qq45-vh27", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "pyca/cryptography has a vulnerable OpenSSL included in cryptography wheels", "Description": "pyca/cryptography's wheels include a statically linked copy of OpenSSL. The versions of OpenSSL included in cryptography 37.0.0-43.0.0 are vulnerable to a security issue. More details about the vulnerability itself can be found in https://openssl-library.org/news/secadv/20240903.txt.\n\nIf you are building cryptography source (\"sdist\") then you are responsible for upgrading your copy of OpenSSL. Only users installing from wheels built by the cryptography project (i.e., those distributed on PyPI) need to update their cryptography versions.\n", "Severity": "MEDIUM", "VendorSeverity": {"ghsa": 2}, "References": ["https://github.com/pyca/cryptography", "https://github.com/pyca/cryptography/security/advisories/GHSA-h4gh-qq45-vh27", "https://openssl-library.org/news/secadv/20240903.txt"], "PublishedDate": "2024-09-03T21:59:48Z", "LastModifiedDate": "2024-09-03T21:59:48Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "CRITICAL", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-42005", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.0.8, 4.2.15", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-42005", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Potential SQL injection in QuerySet.values() and values_list()", "Description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. QuerySet.values() and values_list() methods on models with a JSONField are subject to SQL injection in column aliases via a crafted JSON object key as a passed *arg.", "Severity": "CRITICAL", "CweIDs": ["CWE-89"], "VendorSeverity": {"bitnami": 3, "ghsa": 4, "nvd": 3, "oracle-oval": 2, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L", "V3Score": 7.3}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N", "V3Score": 9.1}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L", "V3Score": 7.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L", "V3Score": 7.3}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-42005", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/32ebcbf2e1fe3e5ba79a6554a167efce81f7422d", "https://github.com/django/django/commit/f4af67b9b41e0f4c117a8741da3abbd1c869ab28", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-70.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://linux.oracle.com/cve/CVE-2024-42005.html", "https://linux.oracle.com/errata/ELSA-2024-12803.html", "https://nvd.nist.gov/vuln/detail/CVE-2024-42005", "https://ubuntu.com/security/notices/USN-6946-1", "https://www.cve.org/CVERecord?id=CVE-2024-42005", "https://www.djangoproject.com/weblog/2024/aug/06/security-releases", "https://www.djangoproject.com/weblog/2024/aug/06/security-releases/"], "PublishedDate": "2024-08-07T15:15:56.22Z", "LastModifiedDate": "2024-10-23T18:22:48.937Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-38875", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "4.2.14, 5.0.7", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-38875", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Potential denial-of-service in django.utils.html.urlize()", "Description": "An issue was discovered in Django 4.2 before 4.2.14 and 5.0 before 5.0.7. urlize and urlizetrunc were subject to a potential denial of service attack via certain inputs with a very large number of brackets.", "Severity": "HIGH", "CweIDs": ["CWE-130"], "VendorSeverity": {"bitnami": 3, "ghsa": 3, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-38875", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/7285644640f085f41d60ab0c8ae4e9153f0485db", "https://github.com/django/django/commit/79f368764295df109a37192f6182fb6f361d85b5", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-56.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-38875", "https://ubuntu.com/security/notices/USN-6888-1", "https://ubuntu.com/security/notices/USN-6888-2", "https://www.cve.org/CVERecord?id=CVE-2024-38875", "https://www.djangoproject.com/weblog/2024/jul/09/security-releases", "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"], "PublishedDate": "2024-07-10T05:15:12.02Z", "LastModifiedDate": "2024-11-21T09:26:54.84Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-39330", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.0.7, 4.2.14", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-39330", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Potential directory-traversal in django.core.files.storage.Storage.save()", "Description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. Derived classes of the django.core.files.storage.Storage base class, when they override generate_filename() without replicating the file-path validations from the parent class, potentially allow directory traversal via certain inputs during a save() call. (Built-in Storage sub-classes are unaffected.)", "Severity": "HIGH", "CweIDs": ["CWE-22"], "VendorSeverity": {"bitnami": 2, "ghsa": 3, "redhat": 1, "ubuntu": 1}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N", "V3Score": 4.3}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N", "V3Score": 4.3}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-39330", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/2b00edc0151a660d1eb86da4059904a0fc4e095e", "https://github.com/django/django/commit/9f4f63e9ebb7bf6cb9547ee4e2526b9b96703270", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-58.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-39330", "https://ubuntu.com/security/notices/USN-6888-1", "https://ubuntu.com/security/notices/USN-6888-2", "https://www.cve.org/CVERecord?id=CVE-2024-39330", "https://www.djangoproject.com/weblog/2024/jul/09/security-releases", "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"], "PublishedDate": "2024-07-10T05:15:12.167Z", "LastModifiedDate": "2024-11-21T09:27:28.523Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-39614", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.0.7, 4.2.14", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-39614", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Potential denial-of-service in django.utils.translation.get_supported_language_variant()", "Description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. get_supported_language_variant() was subject to a potential denial-of-service attack when used with very long strings containing specific characters.", "Severity": "HIGH", "CweIDs": ["CWE-130"], "VendorSeverity": {"bitnami": 3, "ghsa": 3, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-39614", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/17358fb35fb7217423d4c4877ccb6d1a3a40b1c3", "https://github.com/django/django/commit/8e7a44e4bec0f11474699c3111a5e0a45afe7f49", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-59.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-39614", "https://ubuntu.com/security/notices/USN-6888-1", "https://ubuntu.com/security/notices/USN-6888-2", "https://www.cve.org/CVERecord?id=CVE-2024-39614", "https://www.djangoproject.com/weblog/2024/jul/09/security-releases", "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"], "PublishedDate": "2024-07-10T05:15:12.237Z", "LastModifiedDate": "2024-11-21T09:28:06.72Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-53908", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.0.10, 5.1.4, 4.2.17", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-53908", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: Potential SQL injection in HasKey(lhs, rhs) on Oracle", "Description": "An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. Direct usage of the django.db.models.fields.json.HasKey lookup, when an Oracle database is used, is subject to SQL injection if untrusted data is used as an lhs value. (Applications that use the jsonfield.has_key lookup via __ are unaffected.)", "Severity": "HIGH", "CweIDs": ["CWE-89"], "VendorSeverity": {"bitnami": 4, "ghsa": 3, "redhat": 3, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", "V3Score": 9.8}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N", "V3Score": 9.1}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-53908", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-157.yaml", "https://groups.google.com/g/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-53908", "https://ubuntu.com/security/notices/USN-7136-1", "https://www.cve.org/CVERecord?id=CVE-2024-53908", "https://www.djangoproject.com/weblog/2024/dec/04/security-releases", "https://www.djangoproject.com/weblog/2024/dec/04/security-releases/", "https://www.openwall.com/lists/oss-security/2024/12/04/3"], "PublishedDate": "2024-12-06T12:15:18.583Z", "LastModifiedDate": "2025-06-09T19:51:17.797Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-39329", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.0.7, 4.2.14", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-39329", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Username enumeration through timing difference for users with unusable passwords", "Description": "An issue was discovered in Django 5.0 before 5.0.7 and 4.2 before 4.2.14. The django.contrib.auth.backends.ModelBackend.authenticate() method allows remote attackers to enumerate users via a timing attack involving login requests for users with an unusable password.", "Severity": "MEDIUM", "CweIDs": ["CWE-208"], "VendorSeverity": {"bitnami": 2, "ghsa": 2, "redhat": 1, "ubuntu": 1}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 5.3}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 3.7}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-39329", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/07cefdee4a9d1fcd9a3a631cbd07c78defd1923b", "https://github.com/django/django/commit/156d3186c96e3ec2ca73b8b25dc2ef366e38df14", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-57.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-39329", "https://ubuntu.com/security/notices/USN-6888-1", "https://ubuntu.com/security/notices/USN-6888-2", "https://www.cve.org/CVERecord?id=CVE-2024-39329", "https://www.djangoproject.com/weblog/2024/jul/09/security-releases", "https://www.djangoproject.com/weblog/2024/jul/09/security-releases/"], "PublishedDate": "2024-07-10T05:15:12.097Z", "LastModifiedDate": "2024-11-21T09:27:28.3Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-41989", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.0.8, 4.2.15", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-41989", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Memory exhaustion in django.utils.numberformat.floatformat()", "Description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The floatformat template filter is subject to significant memory consumption when given a string representation of a number in scientific notation with a large exponent.", "Severity": "MEDIUM", "CweIDs": ["CWE-400"], "VendorSeverity": {"bitnami": 3, "ghsa": 2, "nvd": 3, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-41989", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/27900fe56f3d3cabb4aeb6ccb82f92bab29073a8", "https://github.com/django/django/commit/fc76660f589ac07e45e9cd34ccb8087aeb11904b", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-67.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-41989", "https://ubuntu.com/security/notices/USN-6946-1", "https://www.cve.org/CVERecord?id=CVE-2024-41989", "https://www.djangoproject.com/weblog/2024/aug/06/security-releases", "https://www.djangoproject.com/weblog/2024/aug/06/security-releases/"], "PublishedDate": "2024-08-07T15:15:56.03Z", "LastModifiedDate": "2025-03-14T19:15:47.077Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-41990", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.0.8, 4.2.15", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-41990", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Potential denial-of-service vulnerability in django.utils.html.urlize()", "Description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.", "Severity": "MEDIUM", "CweIDs": ["CWE-130"], "VendorSeverity": {"bitnami": 3, "ghsa": 2, "nvd": 3, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-41990", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/7b7b909579c8311c140c89b8a9431bf537febf93", "https://github.com/django/django/commit/d0a82e26a74940bf0c78204933c3bdd6a283eb88", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-68.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-41990", "https://ubuntu.com/security/notices/USN-6946-1", "https://www.cve.org/CVERecord?id=CVE-2024-41990", "https://www.djangoproject.com/weblog/2024/aug/06/security-releases", "https://www.djangoproject.com/weblog/2024/aug/06/security-releases/"], "PublishedDate": "2024-08-07T15:15:56.1Z", "LastModifiedDate": "2024-08-07T20:49:50.48Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-41991", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.0.8, 4.2.15", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-41991", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Potential denial-of-service vulnerability in django.utils.html.urlize() and AdminURLFieldWidget", "Description": "An issue was discovered in Django 5.0 before 5.0.8 and 4.2 before 4.2.15. The urlize and urlizetrunc template filters, and the AdminURLFieldWidget widget, are subject to a potential denial-of-service attack via certain inputs with a very large number of Unicode characters.", "Severity": "MEDIUM", "CweIDs": ["CWE-1284", "CWE-130"], "VendorSeverity": {"bitnami": 3, "ghsa": 2, "nvd": 3, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-41991", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/523da8771bce321023f490f70d71a9e973ddc927", "https://github.com/django/django/commit/efea1ef7e2190e3f77ca0651b5458297bc0f6a9f", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-69.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-41991", "https://ubuntu.com/security/notices/USN-6946-1", "https://www.cve.org/CVERecord?id=CVE-2024-41991", "https://www.djangoproject.com/weblog/2024/aug/06/security-releases", "https://www.djangoproject.com/weblog/2024/aug/06/security-releases/"], "PublishedDate": "2024-08-07T15:15:56.16Z", "LastModifiedDate": "2024-08-07T20:48:22.403Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-45230", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.1.1, 5.0.9, 4.2.16", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-45230", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Potential denial-of-service vulnerability in django.utils.html.urlize()", "Description": "An issue was discovered in Django 5.1 before 5.1.1, 5.0 before 5.0.9, and 4.2 before 4.2.16. The urlize() and urlizetrunc() template filters are subject to a potential denial-of-service attack via very large inputs with a specific sequence of characters.", "Severity": "MEDIUM", "CweIDs": ["CWE-120"], "VendorSeverity": {"bitnami": 3, "ghsa": 2, "nvd": 3, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 5.9}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-45230", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/022ab0a75c76ab2ea31dfcc5f2cf5501e378d397", "https://github.com/django/django/commit/813de2672bd7361e9a453ab62cd6e52f96b6525b", "https://github.com/django/django/commit/d147a8ebbdf28c17cafbbe2884f0bc57e2bf82e2", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-102.yaml", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-45230", "https://ubuntu.com/security/notices/USN-6987-1", "https://www.cve.org/CVERecord?id=CVE-2024-45230", "https://www.djangoproject.com/weblog/2024/sep/03/security-releases", "https://www.djangoproject.com/weblog/2024/sep/03/security-releases/"], "PublishedDate": "2024-10-08T16:15:11.903Z", "LastModifiedDate": "2025-03-17T15:15:41.52Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-45231", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.1.1, 5.0.9, 4.2.16", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-45231", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-django: Potential user email enumeration via response status on password reset", "Description": "An issue was discovered in Django v5.1.1, v5.0.9, and v4.2.16. The django.contrib.auth.forms.PasswordResetForm class, when used in a view implementing password reset flows, allows remote attackers to enumerate user e-mail addresses by sending password reset requests and observing the outcome (only when e-mail sending is consistently failing).", "Severity": "MEDIUM", "CweIDs": ["CWE-203"], "VendorSeverity": {"bitnami": 2, "ghsa": 2, "nvd": 2, "redhat": 1, "ubuntu": 1}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 5.3}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 3.7}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N", "V3Score": 3.7}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-45231", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/3c733c78d6f8e50296d6e248968b6516c92a53ca", "https://github.com/django/django/commit/96d84047715ea1715b4bd1594e46122b8a77b9e2", "https://github.com/django/django/commit/bf4888d317ba4506d091eeac6e8b4f1fcc731199", "https://groups.google.com/forum/#%21forum/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2024-45231", "https://ubuntu.com/security/notices/USN-6987-1", "https://www.cve.org/CVERecord?id=CVE-2024-45231", "https://www.djangoproject.com/weblog/2024/sep/03/security-releases", "https://www.djangoproject.com/weblog/2024/sep/03/security-releases/"], "PublishedDate": "2024-10-08T16:15:11.997Z", "LastModifiedDate": "2025-03-17T18:15:17.73Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-53907", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.1.4, 4.2.17, 5.0.10", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-53907", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: Potential denial-of-service in django.utils.html.strip_tags()", "Description": "An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and 4.2 before 4.2.17. The strip_tags() method and striptags template filter are subject to a potential denial-of-service attack via certain inputs containing large sequences of nested incomplete HTML entities.", "Severity": "MEDIUM", "CweIDs": ["CWE-770"], "VendorSeverity": {"bitnami": 3, "ghsa": 2, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H", "V3Score": 6.5}}, "References": ["https://access.redhat.com/security/cve/CVE-2024-53907", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2024-156.yaml", "https://groups.google.com/g/django-announce", "https://lists.debian.org/debian-lts-announce/2024/12/msg00028.html", "https://nvd.nist.gov/vuln/detail/CVE-2024-53907", "https://ubuntu.com/security/notices/USN-7136-1", "https://ubuntu.com/security/notices/USN-7136-2", "https://www.cve.org/CVERecord?id=CVE-2024-53907", "https://www.djangoproject.com/weblog/2024/dec/04/security-releases", "https://www.djangoproject.com/weblog/2024/dec/04/security-releases/", "https://www.openwall.com/lists/oss-security/2024/12/04/3"], "PublishedDate": "2024-12-06T12:15:17.73Z", "LastModifiedDate": "2024-12-31T18:15:38.657Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-56374", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.1.5, 5.0.11, 4.2.18", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-56374", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: potential denial-of-service vulnerability in IPv6 validation", "Description": "An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and 4.2 before 4.2.18. Lack of upper-bound limit enforcement in strings passed when performing IPv6 validation could lead to a potential denial-of-service attack. The undocumented and private functions clean_ipv6_address and is_valid_ipv6_address are vulnerable, as is the django.forms.GenericIPAddressField form field. (The django.db.models.GenericIPAddressField model field is not affected.)", "Severity": "MEDIUM", "CweIDs": ["CWE-770"], "VendorSeverity": {"bitnami": 2, "ghsa": 2, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L", "V3Score": 5.8}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L", "V3Score": 5.8}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L", "V3Score": 5.8}}, "References": ["http://www.openwall.com/lists/oss-security/2025/01/14/2", "https://access.redhat.com/security/cve/CVE-2024-56374", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/4806731e58f3e8700a3c802e77899d54ac6021fe", "https://github.com/django/django/commit/ad866a1ca3e7d60da888d25d27e46a8adb2ed36e", "https://github.com/django/django/commit/ca2be7724e1244a4cb723de40a070f873c6e94bf", "https://github.com/django/django/commit/e8d4a2005955dcf962193600b53bf461b190b455", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2025-1.yaml", "https://groups.google.com/g/django-announce", "https://lists.debian.org/debian-lts-announce/2025/01/msg00024.html", "https://nvd.nist.gov/vuln/detail/CVE-2024-56374", "https://ubuntu.com/security/notices/USN-7205-1", "https://ubuntu.com/security/notices/USN-7205-2", "https://www.cve.org/CVERecord?id=CVE-2024-56374", "https://www.djangoproject.com/weblog/2025/jan/14/security-releases", "https://www.djangoproject.com/weblog/2025/jan/14/security-releases/"], "PublishedDate": "2025-01-14T19:15:32.51Z", "LastModifiedDate": "2025-01-23T18:15:32.82Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2025-26699", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "4.2.20, 5.0.13, 5.1.7", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-26699", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: Potential denial-of-service vulnerability in django.utils.text.wrap()", "Description": "An issue was discovered in Django 5.1 before 5.1.7, 5.0 before 5.0.13, and 4.2 before 4.2.20. The django.utils.text.wrap() method and wordwrap template filter are subject to a potential denial-of-service attack when used with very long strings.", "Severity": "MEDIUM", "CweIDs": ["CWE-770"], "VendorSeverity": {"bitnami": 2, "ghsa": 2, "redhat": 2, "ubuntu": 2}, "CVSS": {"bitnami": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:L", "V3Score": 5}, "ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:N/I:N/A:L", "V3Score": 5}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H", "V3Score": 7.5}}, "References": ["http://www.openwall.com/lists/oss-security/2025/03/06/12", "https://access.redhat.com/security/cve/CVE-2025-26699", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/advisories/GHSA-p3fp-8748-vqfq", "https://github.com/django/django", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2025-13.yaml", "https://groups.google.com/g/django-announce", "https://lists.debian.org/debian-lts-announce/2025/03/msg00012.html", "https://nvd.nist.gov/vuln/detail/CVE-2025-26699", "https://ubuntu.com/security/notices/USN-7335-1", "https://www.cve.org/CVERecord?id=CVE-2025-26699", "https://www.djangoproject.com/weblog/2025/mar/06/security-releases", "https://www.djangoproject.com/weblog/2025/mar/06/security-releases/"], "PublishedDate": "2025-03-06T19:15:27.683Z", "LastModifiedDate": "2025-03-19T20:15:19.543Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2025-32873", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "4.2.21, 5.1.9, 5.2.1", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-32873", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: Django StripTags Denial of Service", "Description": "An issue was discovered in Django 4.2 before 4.2.21, 5.1 before 5.1.9, and 5.2 before 5.2.1. The django.utils.html.strip_tags() function is vulnerable to a potential denial-of-service (slow performance) when processing inputs containing large sequences of incomplete HTML tags. The template filter striptags is also vulnerable, because it is built on top of strip_tags().", "Severity": "MEDIUM", "CweIDs": ["CWE-770"], "VendorSeverity": {"ghsa": 2, "redhat": 2, "ubuntu": 2}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L", "V3Score": 5.3}}, "References": ["http://www.openwall.com/lists/oss-security/2025/05/07/1", "https://access.redhat.com/security/cve/CVE-2025-32873", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/django/django/commit/9f3419b519799d69f2aba70b9d25abe2e70d03e0", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2025-37.yaml", "https://groups.google.com/g/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2025-32873", "https://ubuntu.com/security/notices/USN-7501-1", "https://ubuntu.com/security/notices/USN-7501-2", "https://www.cve.org/CVERecord?id=CVE-2025-32873", "https://www.djangoproject.com/weblog/2025/may/07/security-releases", "https://www.djangoproject.com/weblog/2025/may/07/security-releases/"], "PublishedDate": "2025-05-08T04:17:18.157Z", "LastModifiedDate": "2025-05-08T14:39:09.683Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2025-48432", "PkgName": "django", "PkgIdentifier": {"PURL": "pkg:pypi/django@4.2.11", "UID": "1f8cab882ab22820"}, "InstalledVersion": "4.2.11", "FixedVersion": "5.2.2, 5.1.10, 4.2.22", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-48432", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "django: Django Path Injection Vulnerability", "Description": "An issue was discovered in Django 5.2 before 5.2.3, 5.1 before 5.1.11, and 4.2 before 4.2.23. Internal HTTP response logging does not escape request.path, which allows remote attackers to potentially manipulate log output via crafted URLs. This may lead to log injection or forgery when logs are viewed in terminals or processed by external systems.", "Severity": "MEDIUM", "CweIDs": ["CWE-117"], "VendorSeverity": {"ghsa": 2, "redhat": 2, "ubuntu": 1}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:N/I:L/A:N", "V3Score": 4}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:C/C:L/I:L/A:N", "V3Score": 5.4}}, "References": ["http://www.openwall.com/lists/oss-security/2025/06/04/5", "http://www.openwall.com/lists/oss-security/2025/06/10/2", "http://www.openwall.com/lists/oss-security/2025/06/10/3", "http://www.openwall.com/lists/oss-security/2025/06/10/4", "https://access.redhat.com/security/cve/CVE-2025-48432", "https://docs.djangoproject.com/en/dev/releases/security", "https://docs.djangoproject.com/en/dev/releases/security/", "https://github.com/django/django", "https://github.com/pypa/advisory-database/tree/main/vulns/django/PYSEC-2025-47.yaml", "https://groups.google.com/g/django-announce", "https://nvd.nist.gov/vuln/detail/CVE-2025-48432", "https://ubuntu.com/security/notices/USN-7555-1", "https://www.cve.org/CVERecord?id=CVE-2025-48432", "https://www.djangoproject.com/weblog/2025/jun/04/security-releases", "https://www.djangoproject.com/weblog/2025/jun/04/security-releases/", "https://www.djangoproject.com/weblog/2025/jun/10/bugfix-releases", "https://www.djangoproject.com/weblog/2025/jun/10/bugfix-releases/"], "PublishedDate": "2025-06-05T03:15:25.563Z", "LastModifiedDate": "2025-06-10T18:15:32.79Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-35195", "PkgName": "requests", "PkgIdentifier": {"PURL": "pkg:pypi/requests@2.31.0", "UID": "2068790f5fa6c273"}, "InstalledVersion": "2.31.0", "FixedVersion": "2.32.0", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-35195", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "requests: subsequent requests to the same host ignore cert verification", "Description": "Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.", "Severity": "MEDIUM", "CweIDs": ["CWE-670"], "VendorSeverity": {"alma": 2, "amazon": 2, "azure": 2, "cbl-mariner": 2, "ghsa": 2, "oracle-oval": 2, "photon": 2, "redhat": 2, "rocky": 2, "ubuntu": 2}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N", "V3Score": 5.6}, "redhat": {"V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N", "V3Score": 5.6}}, "References": ["https://access.redhat.com/errata/RHSA-2025:0012", "https://access.redhat.com/security/cve/CVE-2024-35195", "https://bugzilla.redhat.com/2282114", "https://bugzilla.redhat.com/show_bug.cgi?id=2282114", "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-35195", "https://errata.almalinux.org/8/ALSA-2025-0012.html", "https://errata.rockylinux.org/RLSA-2025:0012", "https://github.com/psf/requests", "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac", "https://github.com/psf/requests/pull/6655", "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56", "https://linux.oracle.com/cve/CVE-2024-35195.html", "https://linux.oracle.com/errata/ELSA-2025-7049.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/", "https://nvd.nist.gov/vuln/detail/CVE-2024-35195", "https://www.cve.org/CVERecord?id=CVE-2024-35195"], "PublishedDate": "2024-05-20T21:15:09.99Z", "LastModifiedDate": "2024-11-21T09:19:54.51Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-47081", "PkgName": "requests", "PkgIdentifier": {"PURL": "pkg:pypi/requests@2.31.0", "UID": "2068790f5fa6c273"}, "InstalledVersion": "2.31.0", "FixedVersion": "2.32.4", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47081", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "requests: Requests vulnerable to .netrc credentials leak via malicious URLs", "Description": "Requests is a HTTP library. Due to a URL parsing issue, Requests releases prior to 2.32.4 may leak .netrc credentials to third parties for specific maliciously-crafted URLs. Users should upgrade to version 2.32.4 to receive a fix. For older versions of Requests, use of the .netrc file can be disabled with `trust_env=False` on one's Requests Session.", "Severity": "MEDIUM", "CweIDs": ["CWE-522"], "VendorSeverity": {"ghsa": 2, "redhat": 2, "ubuntu": 2}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N", "V3Score": 5.3}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N", "V3Score": 5.3}}, "References": ["http://seclists.org/fulldisclosure/2025/Jun/2", "http://www.openwall.com/lists/oss-security/2025/06/03/11", "http://www.openwall.com/lists/oss-security/2025/06/03/9", "http://www.openwall.com/lists/oss-security/2025/06/04/1", "http://www.openwall.com/lists/oss-security/2025/06/04/6", "https://access.redhat.com/security/cve/CVE-2024-47081", "https://github.com/psf/requests", "https://github.com/psf/requests/commit/96ba401c1296ab1dda74a2365ef36d88f7d144ef", "https://github.com/psf/requests/pull/6965", "https://github.com/psf/requests/security/advisories/GHSA-9hjg-9r4m-mvj7", "https://nvd.nist.gov/vuln/detail/CVE-2024-47081", "https://requests.readthedocs.io/en/latest/api/#requests.Session.trust_env", "https://seclists.org/fulldisclosure/2025/Jun/2", "https://www.cve.org/CVERecord?id=CVE-2024-47081", "https://www.openwall.com/lists/oss-security/2025/06/03/9"], "PublishedDate": "2025-06-09T18:15:24.983Z", "LastModifiedDate": "2025-06-12T16:06:47.857Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "HIGH", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2023-43804", "PkgName": "urllib3", "PkgIdentifier": {"PURL": "pkg:pypi/urllib3@1.26.9", "UID": "b07b8e0bc843b252"}, "InstalledVersion": "1.26.9", "FixedVersion": "2.0.6, 1.26.17", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-43804", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "python-urllib3: Cookie request header isn't stripped during cross-origin redirects", "Description": "urllib3 is a user-friendly HTTP client library for Python. urllib3 doesn't treat the `Cookie` HTTP header special or provide any helpers for managing cookies over HTTP, that is the responsibility of the user. However, it is possible for a user to specify a `Cookie` header and unknowingly leak information via HTTP redirects to a different origin if that user doesn't disable redirects explicitly. This issue has been patched in urllib3 version 1.26.17 or 2.0.5.", "Severity": "HIGH", "CweIDs": ["CWE-200"], "VendorSeverity": {"alma": 2, "amazon": 2, "azure": 3, "cbl-mariner": 2, "ghsa": 3, "nvd": 3, "oracle-oval": 2, "photon": 2, "redhat": 2, "rocky": 2, "ubuntu": 2}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N", "V3Score": 5.9}, "nvd": {"V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:N", "V3Score": 8.1}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:H/A:N", "V3Score": 5.9}}, "References": ["https://access.redhat.com/errata/RHSA-2024:2987", "https://access.redhat.com/security/cve/CVE-2023-43804", "https://bugzilla.redhat.com/2158559", "https://bugzilla.redhat.com/2240059", "https://bugzilla.redhat.com/2242493", "https://bugzilla.redhat.com/2249755", "https://bugzilla.redhat.com/2257854", "https://bugzilla.redhat.com/show_bug.cgi?id=2242493", "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-43804", "https://errata.almalinux.org/8/ALSA-2024-2987.html", "https://errata.rockylinux.org/RLSA-2024:2986", "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-192.yaml", "https://github.com/urllib3/urllib3", "https://github.com/urllib3/urllib3/commit/01220354d389cd05474713f8c982d05c9b17aafb", "https://github.com/urllib3/urllib3/commit/644124ecd0b6e417c527191f866daa05a5a2056d", "https://github.com/urllib3/urllib3/security/advisories/GHSA-v845-jxx5-vc9f", "https://linux.oracle.com/cve/CVE-2023-43804.html", "https://linux.oracle.com/errata/ELSA-2024-2987.html", "https://lists.debian.org/debian-lts-announce/2023/10/msg00012.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/I3PR7C6RJ6JUBQKIJ644DMIJSUP36VDY/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NDAGZXYJ7H2G3SB47M453VQVNAWKAEJJ/", "https://nvd.nist.gov/vuln/detail/CVE-2023-43804", "https://security.netapp.com/advisory/ntap-20241213-0007", "https://security.netapp.com/advisory/ntap-20241213-0007/", "https://ubuntu.com/security/notices/USN-6473-1", "https://ubuntu.com/security/notices/USN-6473-2", "https://www.cve.org/CVERecord?id=CVE-2023-43804", "https://www.vicarius.io/vsociety/posts/cve-2023-43804-urllib3-vulnerability-3"], "PublishedDate": "2023-10-04T17:15:10.163Z", "LastModifiedDate": "2024-12-13T14:15:20.57Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2023-45803", "PkgName": "urllib3", "PkgIdentifier": {"PURL": "pkg:pypi/urllib3@1.26.9", "UID": "b07b8e0bc843b252"}, "InstalledVersion": "1.26.9", "FixedVersion": "2.0.7, 1.26.18", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-45803", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "urllib3: Request body not stripped after redirect from 303 status changes request method to GET", "Description": "urllib3 is a user-friendly HTTP client library for Python. urllib3 previously wouldn't remove the HTTP request body when an HTTP redirect response using status 301, 302, or 303 after the request had its method changed from one that could accept a request body (like `POST`) to `GET` as is required by HTTP RFCs. Although this behavior is not specified in the section for redirects, it can be inferred by piecing together information from different sections and we have observed the behavior in other major HTTP client implementations like curl and web browsers. Because the vulnerability requires a previously trusted service to become compromised in order to have an impact on confidentiality we believe the exploitability of this vulnerability is low. Additionally, many users aren't putting sensitive data in HTTP request bodies, if this is the case then this vulnerability isn't exploitable. Both of the following conditions must be true to be affected by this vulnerability: 1. Using urllib3 and submitting sensitive information in the HTTP request body (such as form data or JSON) and 2. The origin service is compromised and starts redirecting using 301, 302, or 303 to a malicious peer or the redirected-to service becomes compromised. This issue has been addressed in versions 1.26.18 and 2.0.7 and users are advised to update to resolve this issue. Users unable to update should disable redirects for services that aren't expecting to respond with redirects with `redirects=False` and disable automatic redirects with `redirects=False` and handle 301, 302, and 303 redirects manually by stripping the HTTP request body.", "Severity": "MEDIUM", "CweIDs": ["CWE-200"], "VendorSeverity": {"alma": 2, "amazon": 2, "azure": 2, "cbl-mariner": 2, "ghsa": 2, "nvd": 2, "oracle-oval": 2, "photon": 2, "redhat": 2, "rocky": 2, "ubuntu": 2}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N", "V3Score": 4.2}, "nvd": {"V3Vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N", "V3Score": 4.2}, "redhat": {"V3Vector": "CVSS:3.1/AV:A/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N", "V3Score": 4.2}}, "References": ["https://access.redhat.com/errata/RHSA-2024:2968", "https://access.redhat.com/security/cve/CVE-2023-45803", "https://bugzilla.redhat.com/2246840", "https://bugzilla.redhat.com/2257028", "https://bugzilla.redhat.com/2257854", "https://bugzilla.redhat.com/show_bug.cgi?id=2246840", "https://bugzilla.redhat.com/show_bug.cgi?id=2257028", "https://bugzilla.redhat.com/show_bug.cgi?id=2257854", "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-45803", "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-52323", "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-22195", "https://errata.almalinux.org/8/ALSA-2024-2968.html", "https://errata.rockylinux.org/RLSA-2024:2968", "https://github.com/pypa/advisory-database/tree/main/vulns/urllib3/PYSEC-2023-212.yaml", "https://github.com/urllib3/urllib3", "https://github.com/urllib3/urllib3/commit/4e50fbc5db74e32cabd5ccc1ab81fc103adfe0b3", "https://github.com/urllib3/urllib3/commit/4e98d57809dacab1cbe625fddeec1a290c478ea9", "https://github.com/urllib3/urllib3/commit/b594c5ceaca38e1ac215f916538fb128e3526a36", "https://github.com/urllib3/urllib3/releases/tag/1.26.18", "https://github.com/urllib3/urllib3/releases/tag/2.0.7", "https://github.com/urllib3/urllib3/security/advisories/GHSA-g4mx-q9vg-27p4", "https://linux.oracle.com/cve/CVE-2023-45803.html", "https://linux.oracle.com/errata/ELSA-2024-2988.html", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4R2Y5XK3WALSR3FNAGN7JBYV2B343ZKB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5F5CUBAN5XMEBVBZPHFITBLMJV5FIJJ5/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PPDPLM6UUMN55ESPQWJFLLIZY4ZKCNRX/", "https://nvd.nist.gov/vuln/detail/CVE-2023-45803", "https://ubuntu.com/security/notices/USN-6473-1", "https://ubuntu.com/security/notices/USN-6473-2", "https://www.cve.org/CVERecord?id=CVE-2023-45803", "https://www.rfc-editor.org/rfc/rfc9110.html#name-get"], "PublishedDate": "2023-10-17T20:15:10.07Z", "LastModifiedDate": "2025-02-13T18:15:32.78Z"}}}, {"code": "VULNERABLE_DEPENDENCY_DEP_FILE", "severity": "MEDIUM", "details": {"file_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\requirements.txt", "results": {"VulnerabilityID": "CVE-2024-37891", "PkgName": "urllib3", "PkgIdentifier": {"PURL": "pkg:pypi/urllib3@1.26.9", "UID": "b07b8e0bc843b252"}, "InstalledVersion": "1.26.9", "FixedVersion": "1.26.19, 2.2.2", "Status": "fixed", "Layer": {}, "SeveritySource": "ghsa", "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-37891", "DataSource": {"ID": "ghsa", "Name": "GitHub Security Advisory pip", "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"}, "Title": "urllib3: proxy-authorization request header is not stripped during cross-origin redirects", "Description": " urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.", "Severity": "MEDIUM", "CweIDs": ["CWE-669"], "VendorSeverity": {"alma": 2, "amazon": 2, "azure": 2, "cbl-mariner": 2, "ghsa": 2, "oracle-oval": 2, "redhat": 2, "rocky": 2, "ubuntu": 1}, "CVSS": {"ghsa": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N", "V3Score": 4.4}, "redhat": {"V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N", "V3Score": 4.4}}, "References": ["https://access.redhat.com/errata/RHSA-2024:8843", "https://access.redhat.com/security/cve/CVE-2024-37891", "https://bugzilla.redhat.com/2292788", "https://bugzilla.redhat.com/show_bug.cgi?id=2292788", "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-37891", "https://errata.almalinux.org/8/ALSA-2024-8843.html", "https://errata.rockylinux.org/RLSA-2024:5309", "https://github.com/urllib3/urllib3", "https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468", "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e", "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf", "https://linux.oracle.com/cve/CVE-2024-37891.html", "https://linux.oracle.com/errata/ELSA-2024-9458.html", "https://nvd.nist.gov/vuln/detail/CVE-2024-37891", "https://security.netapp.com/advisory/ntap-20240822-0003/", "https://ubuntu.com/security/notices/USN-7084-1", "https://ubuntu.com/security/notices/USN-7084-2", "https://www.cve.org/CVERecord?id=CVE-2024-37891", "https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"], "PublishedDate": "2024-06-17T20:15:13.45Z", "LastModifiedDate": "2024-11-21T09:24:28.953Z"}}}], "plugins": [{"name": "PII Plugin", "settings": {"enabled": true, "confidence_threshold": 0.8, "block_on_detection": true, "entities": {"US_PASSPORT": true, "AU_MEDICARE": true, "AU_TFN": true, "AU_ACN": true, "AU_ABN": true, "UK_NHS": true, "US_SSN": true, "US_ITIN": true, "US_DRIVER_LICENSE": true, "US_BANK_NUMBER": true, "MEDICAL_LICENSE": true, "LOCATION": true, "PHONE_NUMBER": true, "NRP": true, "IP_ADDRESS": true, "EMAIL_ADDRESS": true, "IBAN_CODE": true, "CRYPTO": true, "CREDIT_CARD": true, "PERSON": true}}}, {"name": "Secrets Plugin", "settings": {"enabled": true, "block_on_detection": true, "secrets_plugins": [{"name": "SoftlayerDetector"}, {"name": "StripeDetector"}, {"name": "SendGridDetector"}, {"name": "NpmDetector"}, {"name": "KeywordDetector", "keyword_exclude": ""}, {"name": "IbmCosHmacDetector"}, {"name": "DiscordBotTokenDetector"}, {"name": "BasicAuthDetector"}, {"name": "AzureStorageKeyDetector"}, {"name": "ArtifactoryDetector"}, {"name": "AWSKeyDetector"}, {"name": "CloudantDetector"}, {"name": "GitHubTokenDetector"}, {"name": "IbmCloudIamDetector"}, {"name": "JwtTokenDetector"}, {"name": "MailchimpDetector"}, {"name": "PrivateKeyDetector"}, {"name": "SlackDetector"}, {"name": "SquareOAuthDetector"}, {"name": "TwilioKeyDetector"}, {"name": "Base64HighEntropyString", "limit": 4.5}, {"name": "HexHighEntropyString", "limit": 3.0}]}}, {"name": "License Plugin for Dependency Files", "settings": {"enabled": true, "accepted_licenses": ["Apache License 2.0", "Apache Software License", "Apache 2.0", "Apache-2.0", "BSD", "BSD License", "BSD 3-Clause", "BSD-3-Clause", "GNU Library or Lesser General Public License (LGPL)", "Microsoft Public License", "MIT", "MIT License", "Python Software Foundation License", "ISC License (ISCL)", "MIT-0"]}}, {"name": "CVE Plugin for Dependency Files", "settings": {"enabled": true, "block_on_critical": true, "block_on_high": true, "block_on_medium": true, "block_on_low": true, "trivy_binary_path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\trivy.exe"}}], "notebooks": ["C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\nbdefense_test_plugins-checkpoint.ipynb", "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\nbdefense_test_plugins.ipynb", "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\test-cve.ipynb", "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\test-license.ipynb"], "notebook_issues": [{"path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\nbdefense_test_plugins-checkpoint.ipynb", "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 1, "cell_type": "SOURCE", "scrubbed_content": "# PII Test Section\nname = \"[PII]\"\nemail = \"[PII]\"\nphone = \"+1-800-123-4567\"\n"}, "location": "INPUT", "details": {"description": "A total of 2 PII found in cell number 1", "summary_field": {"PERSON": 1, "EMAIL_ADDRESS": 1}}, "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 1, "cell_type": "SOURCE", "scrubbed_content": "# PII Test Section\nname = \"[PII]\"\nemail = \"[PII]\"\nphone = \"+1-800-123-4567\"\n"}, "line_index": 1, "location": "INPUT", "character_start_index": 8, "character_end_index": 16, "details": null}, {"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 1, "cell_type": "SOURCE", "scrubbed_content": "# PII Test Section\nname = \"[PII]\"\nemail = \"[PII]\"\nphone = \"+1-800-123-4567\"\n"}, "line_index": 2, "location": "INPUT", "character_start_index": 9, "character_end_index": 29, "details": null}]}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 2, "location": "INPUT", "character_start_index": 12, "character_end_index": 26, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 1, "location": "INPUT", "character_start_index": 11, "character_end_index": 31, "details": {"description": "AWS Access Key", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 1, "location": "INPUT", "character_start_index": 11, "character_end_index": 31, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 3, "location": "INPUT", "character_start_index": 16, "character_end_index": 46, "details": {"description": "Secret Keyword", "summary_field": null}}]}, {"path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\nbdefense_test_plugins.ipynb", "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 1, "cell_type": "SOURCE", "scrubbed_content": "# PII Test Section\nname = \"[PII]\"\nemail = \"[PII]\"\nphone = \"+1-800-123-4567\"\n"}, "location": "INPUT", "details": {"description": "A total of 2 PII found in cell number 1", "summary_field": {"PERSON": 1, "EMAIL_ADDRESS": 1}}, "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 1, "cell_type": "SOURCE", "scrubbed_content": "# PII Test Section\nname = \"[PII]\"\nemail = \"[PII]\"\nphone = \"+1-800-123-4567\"\n"}, "line_index": 1, "location": "INPUT", "character_start_index": 8, "character_end_index": 16, "details": null}, {"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 1, "cell_type": "SOURCE", "scrubbed_content": "# PII Test Section\nname = \"[PII]\"\nemail = \"[PII]\"\nphone = \"+1-800-123-4567\"\n"}, "line_index": 2, "location": "INPUT", "character_start_index": 9, "character_end_index": 29, "details": null}]}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 1, "location": "INPUT", "character_start_index": 11, "character_end_index": 31, "details": {"description": "AWS Access Key", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 8, "location": "INPUT", "character_start_index": 16, "character_end_index": 46, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 2, "location": "INPUT", "character_start_index": 16, "character_end_index": 19, "details": {"description": "GitHub Token", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 1, "location": "INPUT", "character_start_index": 11, "character_end_index": 31, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 2, "location": "INPUT", "character_start_index": 16, "character_end_index": 60, "details": {"description": "Base64 High Entropy String", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 7, "location": "INPUT", "character_start_index": 12, "character_end_index": 26, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 3, "location": "INPUT", "character_start_index": 18, "character_end_index": 58, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 4, "location": "INPUT", "character_start_index": 21, "character_end_index": 53, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 4, "location": "INPUT", "character_start_index": 21, "character_end_index": 53, "details": {"description": "Base64 High Entropy String", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 2, "cell_type": "SOURCE", "scrubbed_content": "# Secrets Test Section\napi_key = \"AK..LE\"\nGITHUB_TOKEN = \"gh..hp_1234567890abcdefghijklmnopqrstuvwxyzABCD\"\nGOOGLE_API_KEY = \"AI..UV\"\nSTRIPE_SECRET_KEY = \"sk..dc\"\nSTRIPE_SECRET_KEY = \"sk_test_4eC39HqLyjWDarjtT1zdp7dc\"\n\npassword = \"su..23\"\nsecret_token = \"gh..en\"\n"}, "line_index": 3, "location": "INPUT", "character_start_index": 18, "character_end_index": 58, "details": {"description": "Base64 High Entropy String", "summary_field": null}}]}, {"path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\test-cve.ipynb", "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 0, "cell_type": "SOURCE", "scrubbed_content": "import [PII]\nimport matplotlibXtns\nclient_secret = \"e2..9a\"\nprint(\"output\")"}, "location": "INPUT", "details": {"description": "A total of 1 PII found in cell number 0", "summary_field": {"PERSON": 1}}, "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 0, "cell_type": "SOURCE", "scrubbed_content": "import [PII]\nimport matplotlibXtns\nclient_secret = \"e2..9a\"\nprint(\"output\")"}, "line_index": 0, "location": "INPUT", "character_start_index": 7, "character_end_index": 13, "details": null}]}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 0, "cell_type": "SOURCE", "scrubbed_content": "import [PII]\nimport matplotlibXtns\nclient_secret = \"e2..9a\"\nprint(\"output\")"}, "line_index": 2, "location": "INPUT", "character_start_index": 17, "character_end_index": 57, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 0, "cell_type": "SOURCE", "scrubbed_content": "import [PII]\nimport matplotlibXtns\nclient_secret = \"e2..9a\"\nprint(\"output\")"}, "line_index": 2, "location": "INPUT", "character_start_index": 17, "character_end_index": 57, "details": {"description": "Hex High Entropy String", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 1, "cell_type": "PLAINTEXT", "scrubbed_content": "'e2..9a'", "output_index": 0}, "line_index": 0, "location": "OUTPUT", "character_start_index": 1, "character_end_index": 41, "details": {"description": "Hex High Entropy String", "summary_field": null}}]}, {"path": "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\test-license.ipynb", "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 0, "cell_type": "SOURCE", "scrubbed_content": "import [PII]\nimport matplotlib.pyplot as plt\nclient_secret = \"e2..9a\"\nprint(client_secret)\n"}, "location": "INPUT", "details": {"description": "A total of 1 PII found in cell number 0", "summary_field": {"PERSON": 1}}, "issues": [{"code": "PII_FOUND", "severity": "HIGH", "cell": {"cell_index": 0, "cell_type": "SOURCE", "scrubbed_content": "import [PII]\nimport matplotlib.pyplot as plt\nclient_secret = \"e2..9a\"\nprint(client_secret)\n"}, "line_index": 0, "location": "INPUT", "character_start_index": 7, "character_end_index": 13, "details": null}]}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 0, "cell_type": "SOURCE", "scrubbed_content": "import [PII]\nimport matplotlib.pyplot as plt\nclient_secret = \"e2..9a\"\nprint(client_secret)\n"}, "line_index": 2, "location": "INPUT", "character_start_index": 17, "character_end_index": 57, "details": {"description": "Secret Keyword", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 0, "cell_type": "SOURCE", "scrubbed_content": "import [PII]\nimport matplotlib.pyplot as plt\nclient_secret = \"e2..9a\"\nprint(client_secret)\n"}, "line_index": 2, "location": "INPUT", "character_start_index": 17, "character_end_index": 57, "details": {"description": "Hex High Entropy String", "summary_field": null}}, {"code": "SECRETS", "severity": "CRITICAL", "cell": {"cell_index": 1, "cell_type": "PLAINTEXT", "scrubbed_content": "'e2..9a'", "output_index": 0}, "line_index": 0, "location": "OUTPUT", "character_start_index": 1, "character_end_index": 41, "details": {"description": "Hex High Entropy String", "summary_field": null}}]}]}
